Algoritmo "alturas"

Var
   p1, p2 : caracter
   a1, a2 : real


Inicio
   escreva("nome da primeira pessoa: ")
   leia(p1)
   
   escreva("altura primeira pessoa: ")
   leia(a1)


   escreva("nome da ssegunda pessoa: ")
   leia(p2)
   
    escreva("altura segunda pessoa: ")
   leia(a2)
   
   se a1 > a2 entao
   escreva("este é o mais alto: ", p1, a1)
   senao
   escreva("este é o mais alto: ", p2, a2)
   
   fimse
   
   


Fimalgoritmo