algoritmo "semnome"
var
p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15 : caracter
c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15 : real
m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15 : real
media : real
mediana : real

inicio

       escreva("1 pais :")
       leia(p1)
   escreval("casos do 1 pais :")
   leia(c1)
escreval("mortes do 1 pais :")
leia(m1)

       escreva("2 pais :")
       leia(p2)
   escreval("casos do 2 pais :")
   leia(c2)
escreval("mortes do 2 pais :")
leia(m2)

       escreva("3 pais :")
       leia(p3)
    escreval("casos do 3 pais :")
    leia(c3)
escreval("mortes do 3 pais :")
leia(m3)

       escreva("4 pais :")
       leia(p4)
    escreval("casos do 4 pais :")
    leia(c4)
escreval("mortes do 4 pais :")
leia(m4)

       escreva("5 pais :")
       leia(p5)
   escreval("casos do 5 pais :")
   leia(c5)
escreval("mortes do 5 pais :")
leia(m5)

       escreva("6 pais :")
       leia(p6)
   escreval("casos do 6 pais :")
   leia(c6)
escreval("mortes do 6 pais :")
leia(m6)

       escreva("7 pais :")
       leia(p7)
   escreval("casos do 7 pais :")
   leia(c7)
escreval("mortes do 7 pais :")
leia(m7)

       escreva("8 pais :")
       leia(p8)
   escreval("casos do 8 pais :")
   leia(c8)
escreval("mortes do 8 pais :")
leia(m8)

       escreva("9 pais :")
       leia(p9)
   escreval("casos do 9 pais :")
   leia(c9)
escreval("mortes do 9 pais :")
leia(m9)

       escreva("10 pais :")
       leia(p10)
   escreval("casos do 10 pais :")
   leia(c10)
escreval("mortes do 10 pais :")
leia(m10)

       escreva("11 pais :")
       leia(p11)
   escreval("casos do 11 pais :")
   leia(c11)
escreval("mortes do 11 pais :")
leia(m11)

       escreva("12 pais :")
       leia(p12)
   escreval("casos do 12 pais :")
   leia(c12)
escreval("mortes do 12 pais :")
leia(m12)

       escreva("13 pais :")
       leia(p13)
   escreval("casos do 13 pais :")
   leia(c13)
escreval("mortes do 13 pais :")
leia(m13)

       escreva("14 pais :")
       leia(p14)
   escreval("casos do 14 pais :")
   leia(c14)
escreval("mortes do 14 pais :")
leia(m14)

       escreva("15 pais :")
       leia(p15)
   escreval("casos do 15 pais :")
   leia(c15)
escreval("mortes do 15 pais :")
leia(m15)


    escreval("pais ", p1," - casos", c1," - mortes", m1)
    escreval("pais ", p2," - casos", c2," - mortes", m2)
    escreval("pais ", p3," - casos", c3," - mortes", m3)
    escreval("pais ", p4," - casos", c4," - mortes", m4)
    escreval("pais ", p5," - casos", c5," - mortes", m5)
    escreval("pais ", p6," - casos", c6," - mortes", m6)
    escreval("pais ", p7," - casos", c7," - mortes", m7)
    escreval("pais ", p8," - casos", c8," - mortes", m8)
    escreval("pais ", p9," - casos", c9," - mortes", m9)
    escreval("pais ", p10," - casos", c10," - mortes", ,m10)
    escreval("pais ", p11," - casos", c11," - mortes", ,m11)
    escreval("pais ", p12," - casos", c12," - mortes", ,m12)
    escreval("pais ", p13," - casos", c13," - mortes", ,m13)
    escreval("pais ", p14," - casos", c14," - mortes", ,m14)
    escreval("pais ", p15," - casos", c15," - mortes", ,m15)



media<- ((c1+c2+c3+c4+c5+c6+c7+c8+c9+c10+c11+c12+c13+c14+c15)/15)
mediana<- ((c7+c8)/2)



fimalgoritmo