algoritmo "par impár"


var
x, z : inteiro


inicio

     escreva("digite o primeiro numero :")
     leia(x)

     escreva("digite o segundo numero :")
     leia(z)

     se x mod 2 = 0 entao
     escreval("numero 1 é ", x," par")
     senao
     escreval("numero 1 é ", x," impar")
  fimse
  
     se z mod 2 = 0 entao
      escreval("numero 2 é ", z," par")
     senao
     escreval("numero 2 é ", z," impar")
  fimse


fimalgoritmo